"""
Reward functions for R-Align training.

Reward = 1.0 iff the GenRM predicts the correct preference label *and* a
Meta-Judge (LLM judge called over an OpenAI-compatible HTTP API) declares
the GenRM rationale consistent with the Golden Rationale, else 0.0.

The async variant `r_align_reward_async` is preferred: GRPOTrainer runs all
async reward functions for a rollout batch in parallel via asyncio.gather,
so API latency overlaps across the whole batch instead of serializing.

Expected dataset columns (forwarded as kwargs by GRPOTrainer):
    - gt_label:     "A" | "B"
    - gt_judgment:  golden rationale (o*)
    - response_A:   str
    - response_B:   str
    - prompt:       list[dict]  (conversational)

Environment variables:
    METAJUDGE_BASE_URL   OpenAI-compatible endpoint root, e.g. https://api.openai.com/v1
    METAJUDGE_API_KEY    API key
    METAJUDGE_MODEL      Model name, defaults to gemini-3-pro-thinking
    METAJUDGE_MAX_TOKENS Max completion tokens (default 2048)
    METAJUDGE_TIMEOUT    Per-request timeout seconds (default 120)
    METAJUDGE_RETRIES    Retry count on transient failures (default 3)
"""

from __future__ import annotations

import asyncio
import os
import re

import httpx


META_JUDGE_PROMPT = """# Role
You are a professional RLHF data quality evaluation expert. Your task is to assess whether the "evaluation rationale" generated by a Reward Model (GenRM) accurately captures the core reasoning of a human expert (Golden Judge).

# Input Data

Below are the conversation context and the responses from two models:

{context_and_responses}

Below is the evaluation provided by the human expert (Golden Judge):
<golden_judge>
{golden_explanation}
</golden_judge>

Below is the evaluation generated by the model under review (GenRM):
<genrm_output>
{genrm_explanation}
</genrm_output>

# Evaluation Steps (Chain of Thought)

Please take a deep breath and proceed step by step with the following analysis:

1. **Extract Golden Key Points**: Read the explanation in <golden_judge> and identify the core decisive factors (Key Discriminators) that led to the final judgment (e.g., A > B).
2. **Check GenRM Coverage**: Read <genrm_output> and determine whether it explicitly identifies the above decisive factors. If GenRM only provides vague statements without pointing out the specific issues emphasized by Golden, this is Incorrect.
3. **Final Decision**: If GenRM's reasoning is consistent with Golden's core logic (even if phrased differently), verdict is Correct. If GenRM misses key error points, fabricates reasons, or conflicts with Golden's logic, verdict is Incorrect.

# Output Format

<golden_key_points>
Briefly summarize the key points that the Golden Judge considers critical in distinguishing A from B
</golden_key_points>
<genrm_analysis>
Analyze whether GenRM mentioned the above key points
</genrm_analysis>
<final_verdict>
Correct OR Incorrect
</final_verdict>
"""


_LABEL_RE = re.compile(r"\\?boxed\{\s*([AB])\s*\}", re.IGNORECASE)


def extract_label(text: str) -> str | None:
    if not text:
        return None
    m = _LABEL_RE.search(text)
    return m.group(1).upper() if m else None


def _user_text(prompt) -> str:
    """Pull the `user` turn out of a conversational prompt; fallback to str()."""
    if isinstance(prompt, list):
        for turn in prompt:
            if turn.get("role") == "user":
                return turn.get("content", "")
    return str(prompt)


def _completion_text(completion) -> str:
    if isinstance(completion, list):
        return "".join(t.get("content", "") for t in completion if t.get("role") == "assistant")
    return str(completion)


def _parse_verdict(meta_judge_output: str) -> bool:
    try:
        verdict = meta_judge_output.split("<final_verdict>", 1)[1].split("</final_verdict>", 1)[0].strip().lower()
        return verdict.startswith("correct")
    except (IndexError, AttributeError):
        return False


async def _call_meta_judge(client: httpx.AsyncClient, *, base_url: str, api_key: str, model: str,
                           max_tokens: int, prompt: str, retries: int) -> str:
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.0,
        "max_tokens": max_tokens,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            resp = await client.post(f"{base_url.rstrip('/')}/chat/completions", json=payload, headers=headers)
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"]
        except Exception as e:
            last_err = e
            await asyncio.sleep(min(2 ** attempt, 30))
    raise RuntimeError(f"Meta-Judge call failed after {retries} retries: {last_err}")


async def r_align_reward_async(prompts, completions, **kwargs) -> list[float]:
    """Async R-Align reward. Returns one float per (prompt, completion) pair."""
    base_url = os.environ["METAJUDGE_BASE_URL"]
    api_key = os.environ["METAJUDGE_API_KEY"]
    model = os.environ.get("METAJUDGE_MODEL", "gemini-3-pro-thinking")
    max_tokens = int(os.environ.get("METAJUDGE_MAX_TOKENS", "2048"))
    timeout = float(os.environ.get("METAJUDGE_TIMEOUT", "120"))
    retries = int(os.environ.get("METAJUDGE_RETRIES", "3"))

    gt_labels = kwargs["gt_label"]
    gt_judgments = kwargs["gt_judgment"]

    rewards: list[float | None] = [None] * len(prompts)
    tasks: list[tuple[int, asyncio.Task]] = []

    async with httpx.AsyncClient(timeout=timeout) as client:
        for idx, (prompt, completion, gt_label, gt_judgment) in enumerate(
            zip(prompts, completions, gt_labels, gt_judgments, strict=True)
        ):
            comp_text = _completion_text(completion)
            pred_label = extract_label(comp_text)

            # Hard gate on label correctness — only spend API calls when label matches.
            if pred_label is None or pred_label != gt_label.strip().upper():
                rewards[idx] = 0.0
                continue

            meta_prompt = META_JUDGE_PROMPT.format(
                context_and_responses=_user_text(prompt),
                golden_explanation=gt_judgment,
                genrm_explanation=comp_text,
            )
            tasks.append((
                idx,
                asyncio.create_task(_call_meta_judge(
                    client, base_url=base_url, api_key=api_key, model=model,
                    max_tokens=max_tokens, prompt=meta_prompt, retries=retries,
                )),
            ))

        for idx, task in tasks:
            try:
                output = await task
                rewards[idx] = 1.0 if _parse_verdict(output) else 0.0
            except Exception:
                rewards[idx] = 0.0  # Treat API failure as "not verified"

    return [float(r) for r in rewards]


def label_accuracy_reward(prompts, completions, **kwargs) -> list[float]:
    """Cheap 0/1 reward on label only — useful as a baseline or co-reward."""
    gt_labels = kwargs["gt_label"]
    out = []
    for completion, gt_label in zip(completions, gt_labels, strict=True):
        pred = extract_label(_completion_text(completion))
        out.append(1.0 if pred is not None and pred == gt_label.strip().upper() else 0.0)
    return out
